name: cosmosdb

on:
  push

jobs:
  docker-compose-up:
    name: Docker compose up CosmosDB
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04] 
    runs-on: ${{ matrix.os }}
    steps:
    
      - name: Checkout Branch Head
        uses: actions/checkout@v3

      - name: Run docker-compose up
        run: docker-compose up -d
        shell: bash
        
      - name: Run docker-compose up
        shell: bash
        run: |
          sleep 60
          docker ps -a
          docker logs azure-cosmosdb