name: cosmosdb

on:
  push

jobs:
  docker-compose-up:
    name: Docker compose up CosmosDB
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Branch Head
        uses: actions/checkout@v2.3.1

      - name: Run docker-compose up
        run: docker-compose up -d
        shell: bash
        
      - name: Run docker-compose up
        shell: bash
        run: |
          sleep 60
          docker ps -a
          docker logs azure-cosmosdb